// Suggestions de métiers pour le sélecteur de secteur du formulaire de scan.
// Le champ reste in fine en texte libre : n'importe quel métier au monde
// peut être recherché, cette liste ne sert qu'à accélérer la saisie des cas
// fréquents en les regroupant par catégorie.
export interface CategorieMetiers {
  id: string;
  label: string;
  metiers: string[];
}

export const CATEGORIES_METIERS: CategorieMetiers[] = [
  {
    id: "alimentation",
    label: "Alimentation & restauration",
    metiers: [
      "Restaurants",
      "Bars & pubs",
      "Cafés",
      "Boulangeries",
      "Pâtisseries",
      "Chocolatiers",
      "Traiteurs",
      "Food trucks",
      "Pizzerias",
      "Crêperies",
      "Glaciers",
      "Cavistes",
      "Torréfacteurs",
      "Épiceries fines",
      "Primeurs",
      "Boucheries",
      "Charcuteries",
      "Poissonneries",
      "Fromageries",
    ],
  },
  {
    id: "hotellerie",
    label: "Hôtellerie & tourisme",
    metiers: [
      "Hôtels & chambres d'hôtes",
      "Gîtes ruraux",
      "Campings",
      "Agences de voyage",
      "Offices de tourisme",
      "Loueurs de vacances",
      "Guides touristiques",
    ],
  },
  {
    id: "beaute",
    label: "Beauté & bien-être",
    metiers: [
      "Salons de coiffure",
      "Barbiers",
      "Instituts de beauté",
      "Spas & bien-être",
      "Salons de manucure",
      "Salons de tatouage",
      "Épilation esthétique",
      "Parfumeries",
    ],
  },
  {
    id: "sante",
    label: "Santé",
    metiers: [
      "Dentistes",
      "Ostéopathes",
      "Kinésithérapeutes",
      "Médecins généralistes",
      "Pharmacies",
      "Vétérinaires",
      "Opticiens",
      "Audioprothésistes",
      "Podologues",
      "Sages-femmes",
      "Psychologues",
      "Nutritionnistes",
      "Infirmiers libéraux",
      "Cliniques vétérinaires",
      "Laboratoires d'analyses médicales",
    ],
  },
  {
    id: "sport",
    label: "Sport & fitness",
    metiers: [
      "Salles de sport",
      "Coachs sportifs",
      "Clubs de yoga",
      "Clubs de pilates",
      "Écoles de danse",
      "Piscines",
      "Clubs d'escalade",
      "Terrains de padel",
      "Golfs",
      "Écoles d'équitation",
    ],
  },
  {
    id: "batiment",
    label: "Bâtiment & artisanat",
    metiers: [
      "Artisans du bâtiment",
      "Plombiers",
      "Électriciens",
      "Peintres en bâtiment",
      "Menuisiers",
      "Serruriers",
      "Couvreurs",
      "Maçons",
      "Carreleurs",
      "Plâtriers",
      "Chauffagistes",
      "Climaticiens",
      "Vitriers",
      "Paysagistes",
      "Terrassiers",
      "Charpentiers",
      "Ébénistes",
      "Ferronniers",
      "Métreurs",
      "Poseurs de cuisine",
      "Ramoneurs",
      "Diagnostiqueurs immobiliers",
    ],
  },
  {
    id: "automobile",
    label: "Automobile",
    metiers: [
      "Garages automobiles",
      "Concessionnaires automobiles",
      "Loueurs de véhicules",
      "Carrossiers",
      "Contrôle technique",
      "Auto-écoles",
      "Vendeurs de pièces auto",
      "Vitrages automobiles",
      "Lavages auto",
    ],
  },
  {
    id: "commerces",
    label: "Commerces & mode",
    metiers: [
      "Bijouteries",
      "Librairies",
      "Fleuristes",
      "Cordonniers",
      "Boutiques de vêtements",
      "Boutiques de chaussures",
      "Magasins de meubles",
      "Magasins de décoration",
      "Animaleries",
      "Magasins de jouets",
      "Magasins de bricolage",
      "Magasins bio",
      "Magasins de sport",
      "Magasins d'électroménager",
      "Magasins de téléphonie",
      "Papeteries",
      "Horlogeries",
      "Antiquaires",
      "Brocantes",
    ],
  },
  {
    id: "services-personne",
    label: "Services à la personne",
    metiers: [
      "Toiletteurs pour animaux",
      "Pressings",
      "Déménageurs",
      "Nettoyage professionnel",
      "Crèches",
      "Écoles de musique",
      "Cours particuliers",
      "Baby-sitting",
      "Aide à domicile",
      "Pompes funèbres",
      "Blanchisseries",
    ],
  },
  {
    id: "immobilier-droit",
    label: "Immobilier & droit",
    metiers: [
      "Agences immobilières",
      "Agents immobiliers",
      "Syndics de copropriété",
      "Avocats",
      "Cabinets d'avocats",
      "Notaires",
      "Huissiers de justice",
      "Experts-comptables",
      "Comptables",
      "Courtiers en assurance",
      "Courtiers en crédit",
      "Agences d'intérim",
    ],
  },
  {
    id: "creation",
    label: "Architecture & création",
    metiers: [
      "Architectes",
      "Décorateurs d'intérieur",
      "Photographes",
      "Vidéastes",
      "Graphistes",
      "Designers",
      "Studios d'enregistrement",
      "Agences de communication",
      "Agences web",
      "Développeurs indépendants",
    ],
  },
  {
    id: "industrie",
    label: "Industrie & artisanat de production",
    metiers: [
      "Imprimeurs",
      "Sérigraphes",
      "Menuiseries industrielles",
      "Métallerie",
      "Ateliers de couture",
      "Tailleurs",
      "Cordonneries",
      "Selliers",
    ],
  },
  {
    id: "divers",
    label: "Divers professionnels",
    metiers: [
      "Consultants",
      "Coachs professionnels",
      "Formateurs",
      "Traducteurs",
      "Agences événementielles",
      "Loueurs de salles",
      "DJ & animation événementielle",
      "Éditeurs",
    ],
  },
];

export const METIERS_SUGGERES = CATEGORIES_METIERS.flatMap((c) => c.metiers);
